config/routes.rb
Rails.application.routes.draw do
  resources :foods, only: [:new, :create, :destroy]
  resources :recipes, only: [:new, :show, :index, :create, :destroy] do
    resources :recipes_food, only: [:create, :update]
  end

  resources :inventories, only: [:new, :show, :index, :create] do
    resources :inventories_food, only: [:create, :update]
  end
  delete '/recipes/:recipe_id/recipes_food/:recipe_food_id', to: 'recipes_food#destroy', as: 'delete_recipe_food'
  get '/shopping_lists/:recipe_id', to: 'shopping_lists#index', as: 'shopping_list'
  get '/foods', to: 'foods#index', as: 'foods_index'
  # get '/shopping_lists/:recipe_id/:inventory_id', to: 'shopping_lists#index', as: 'shopping_list'
  get '/public_recipes', to: 'recipes#public', as: 'public_recipes'
  delete '/recipes/:id', to: 'recipes#destroy', as: 'delete_recipe'
  delete '/inventories/:id', to: 'inventories#destroy', as: 'delete_inventory'
  delete '/inventories/:id/inventory_food/:id', to: 'inventories_food#destroy', as: 'delete_inventory_food'
  match '/recipes/:id' => 'recipes#toggle_public', as: :toggle_public, via: :patch

  devise_for :users
  root to: "recipes#public"

end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :users, foreign_key: 'user_id', class_name: 'User'
  has_many :inventory_foods
  has_many :shopping_lists
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  def index
    @inventories = Inventory.where(user_id: current_user.id)
  end

  def destroy
    @inventory = Inventory.includes(:inventory_foods).find(params[:id])
    @inventory.destroy
    redirect_back(fallback_location: root_path)
  end

  def create
    @inventory = Inventory.new(inventory_params)
    @inventory.user_id = current_user.id
    return unless @inventory.save!

    flash.now[:notice] = 'Inventory created successfully'
    redirect_to inventories_path
  end

  def show
    @inventory = Inventory.includes(inventory_foods: :foods).find(params[:id])
    @foods = Food.all
    @inventory_foods = InventoryFood.where(inventory_id: params[:id])
  end

  def inventory_params
    params.require(:inventory).permit(:name)
  end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/_inventories_food.html.erb
<%= form_with url: inventory_inventories_food_index_path(params[:id]), scope: :inventory_foods, class: 'modal-form' do |form| %>
  <%= form.label :quantity %>
  <%= form.number_field :quantity, in: 1.0..100.0%>
  <%= form.label :food_id %>
  <%= form.select :food_id, @foods.collect { |food| [food.name, food.id] }, { :prompt => 'Choose Food'}, class: "form-select", required: true %>
  <%= form.label :add %>
  <%= form.submit "Add"%>
<%end%>

app/views/inventories/index.html.erb
<section class="inventory-index-mother-container">
  <div class="create-inventory-btn-div">
    <%= link_to "<button>Create Inventory</button>".html_safe, new_inventory_path, class: 'add-food'%>
  </div>
  <div class="inventories-body">
    <% @inventories.each do |inventory| %>
    <%= link_to inventory_path(:id => inventory.id) do %>
    <section class="inventories-container">
        <div class="inventory-name-btn-div">
          <h1><%= inventory.name %> </h1>
          <%= button_to 'Remove', delete_inventory_path(inventory.id), method: :delete, data: {turbo_method: :delete} %>
        </div>
        <div>
            <p>
              Lorem Ipsum is simply dummy text of the printing and typesetting industry.
              Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
              when an unknown printer took a galley of type and scrambled it to make a type specimen book.
              It has survived not only five centuries, but also the leap
            </p>
        </div>
    </section>
    <% end %>
    <% end %>
  </div>
</section>

app/views/inventories/new.html.erb
<div class="new-food-container">
    <%= form_with model:Inventory do |form| %>
    <ul>
      <li class="inventory-ul-li">
        <%= form.label :name %>
        <%= form.text_field :name, placeholder: 'e.g Abubabakar Ummar', value: '', class: "inventory-ul-li-item" %>
      </li>
      <li class="inventory-ul-li">
        <%= form.submit "Create Inventory", class: "submit-btn-inventory"%>
      </li>
    </ul>
    <% end %>
  </div>

app/views/inventories/show.html.erb
<div class="Inventories-show-body">
    <section class="show-header">
        <h1><%= @inventory.name %></h1>
        <div class="add-food-btn-div">
            <button class="click-btn-inventory-food">Add Food</button>
        </div>
    </section>
    <section class="show-table-container">
        <table>
          <tr>
            <th>Food</th>
            <th>Quantity</th>
            <th>Actions</th>
          </tr>
          <% @inventory_foods.each do |inventory| %>
          <tr>
              <td><%= inventory.foods.name %></td>
              <td><%= inventory.quantity %></td>
              <td>
                <%= button_to "Remove", delete_inventory_food_path(inventory.id), method: :delete, data: {turbo_method: :delete} %>
              </td>
          </tr>
          <% end %>
        </table>
    </section>
</div>
<div class="modal">
  <div class="modal-content">
  <button class="close_btn">X</button>
  <div>
    <span>Select an ingredient:</span>
    <%= render 'inventories_food'%>
  </div>
</div>



<script>
  document.querySelector('.click-btn-inventory-food').addEventListener('click', (event) => {
    document.querySelector('.modal').style.visibility = 'visible'
    document.querySelector('#body').style.overflow = 'hidden'
  })

  document.querySelector('.close_btn').addEventListener('click', (event) => {
    document.querySelector('.modal').style.visibility = 'hidden'
    document.querySelector('#body').style.overflow = 'scroll'
  })
</script>