config/routes.rb
Rails.application.routes.draw do
  resources :foods, only: [:new, :create, :destroy]
  resources :recipes, only: [:new, :show, :index, :create, :destroy] do
    resources :recipes_food, only: [:create, :update]
  end

  resources :inventories, only: [:new, :show, :index, :create] do
    resources :inventories_food, only: [:create, :update]
  end
  delete '/recipes/:recipe_id/recipes_food/:recipe_food_id', to: 'recipes_food#destroy', as: 'delete_recipe_food'
  get '/shopping_lists/:recipe_id', to: 'shopping_lists#index', as: 'shopping_list'
  get '/foods', to: 'foods#index', as: 'foods_index'
  # get '/shopping_lists/:recipe_id/:inventory_id', to: 'shopping_lists#index', as: 'shopping_list'
  get '/public_recipes', to: 'recipes#public', as: 'public_recipes'
  delete '/recipes/:id', to: 'recipes#destroy', as: 'delete_recipe'
  delete '/inventories/:id', to: 'inventories#destroy', as: 'delete_inventory'
  delete '/inventories/:id/inventory_food/:id', to: 'inventories_food#destroy', as: 'delete_inventory_food'
  match '/recipes/:id' => 'recipes#toggle_public', as: :toggle_public, via: :patch

  devise_for :users
  root to: "recipes#public"

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_foods
  has_many :shopping_lists
  belongs_to :users, foreign_key: 'user_id', class_name: 'User'

  def self.total_amount(recipe)
    total_amount = 0
    recipe.recipe_foods.each do |recipe_food|
      food = recipe_food.foods
      total_amount += recipe_food.quantity * food.price
    end
    total_amount
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    return unless @recipe.save!

    flash.now[:notice] = 'Recipe created successfully'
    redirect_to recipes_path
  end

  def destroy
    @recipe = Recipe.includes(:recipe_foods).find(params[:id])
    @recipe.destroy
    redirect_to recipes_path
  end

  def show
    @recipe = Recipe.includes(:recipe_foods).find(params[:id])
    @foods = Food.all
    @recipe_foods = RecipeFood.where(recipe_id: params[:id])
    @inventories = Inventory.all
  end

  def public
    @public_recipes = Recipe.where(public: true).order(created_at: :desc)
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end

  def toggle_public
    @recipe = Recipe.includes(:users).find(params[:id])
    @recipe.public = !@recipe.public

    redirect_to recipe_path(@recipe.id), notice: 'Recipe updated' if @recipe.save
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_recipes_food.html.erb
<%= form_with url: recipe_recipes_food_index_path(params[:id]), scope: :recipe_foods, class: 'modal-form' do |form| %>
  <%= form.label :quantity %>
  <%= form.number_field :quantity, in: 1.0..100.0%>
  <%= form.label :food_id %>
  <%= form.select :food_id, @foods.collect { |food| [food.name, food.id] }, { :prompt => 'Choose Food'}, class: "form-select", required: true %>
  <%= form.label :add %>
  <%= form.submit "Add"%>
<%end%>

app/views/recipes/_shopping_list.html.erb
<%= form_with url: shopping_list_path(recipe_id: @recipe), method: :get, id: "shopping-form" do |form| %>
  <div class="generate-shopping-list-div">
    <%= form.select :inventory_id, @inventories.collect { |inventory| [inventory.name, inventory.id] }, { :prompt => 'Click to see inventories'}, required: true, class: "see-inventories" %>
    <%= form.submit "Generate"%>
  </div>
  <% end %>

<script>
  const form = document.getElementById("shopping-form");

  const select = form.elements["shopping_list[inventory_id]"];

  select.addEventListener("change", function() {
    const inventoryId = select.value;

    form.action = "<%= shopping_list_path(recipe_id: @recipe) %>?" + "inventory_id=" + inventoryId;
  });
</script>

app/views/recipes/index.html.erb
<div class="recipes-index-container">
<%= link_to "<button>Create a New recipe</button>".html_safe, new_recipe_path, class: 'add-recipe'%>
   <% @recipes.each_with_index do |recipe, index| %>
   <% if can? :read, recipe %>
      <%= link_to recipe_path(:id => recipe.id) do %>
      <section class='recipe-index-div'>
        <div class="recipe-index-title">
        <h2>Recipe <%= index + 1 %></h2>
        <% if can? :destroy, recipe %>
          <%= button_to 'Remove', delete_recipe_path(recipe.id), method: :delete, data: {turbo_method: :delete} %>
        <%end%>
        </div>
        <div class="recipe-index-content">
            <h1>Description for the recipe</h1>
            <p><%= recipe.description %></p>
        </div>
      </section>
      <% end %>
      <% end %>
   <% end %>
</div>

app/views/recipes/new.html.erb
<div class="new-recipe-container">
  <%= form_with model:Recipe do |form| %>
  <ul>
    <li>
      <%= form.label :name, class: "custom-control-label" %>
      <%= form.text_field :name, placeholder: 'e.g Diego Garcia', value: '', class: "new-recipe-form-li-item" %>
    </li>
    <li>
      <%= form.label :preparation_time, class: "custom-control-label" %>
      <%= form.text_field :preparation_time, placeholder: 'e.g 2 hours', class: "new-recipe-form-li-item" %> 
    </li>
    <li>
      <%= form.label :cooking_time, class: "custom-control-label" %>
      <%= form.text_field :cooking_time, placeholder: 'e.g 40 minutes', class: "new-recipe-form-li-item" %> 
    </li>
    <li>
      <%= form.label :description, class: "custom-control-label" %>
      <%= form.text_area :description, placeholder: 'Write down the steps to prepare this recipe here.', value: '', class: "new-recipe-form-li-item" %> 
    </li>
    <li>
      <%= form.label :public, class: "custom-control-label" %>:
      <%= form.check_box :public, class: "custom-control-input", id: "customSwitch1" %>
    </li>
    <li>
      <%= form.submit "Create Recipe", class:"submit-button"%>
    </li>
  </ul>
  <% end %>
</div>

app/views/recipes/public.html.erb
<div class="public-recipes-container">
  <h1 class="public-recipes-header">Public Recipes</h1>
  <% @public_recipes.each do |public_recipe| %>
  <%= link_to recipe_path(:id => public_recipe.id) do %>
    <section class='public-recipe-div'>
      <div class="public-recipe-title">
        <h1><%= public_recipe.name %></h1>
        <h2>By: <%= public_recipe.users.name %></h2>
      </div>
      <div class="public-recipe-content">
          <h1>Total Food items: X</h1>
          <p>Total Price: $<%= Recipe.total_amount(public_recipe) %></p>
      </div>
    </section>
    <%end%>
  <%end%>
</div>

app/views/recipes/show.html.erb
<div class="recipes-show-mother-container">
<section class="recipe-show-container">
  <h1 class="recipe-show-header">Recipe <%= @recipe.name %> </h1>
  <div class="public-btn-header-div">
    <h1>Preparation Time: <%= @recipe.preparation_time %> </h1>
    <section class="public-btn-div">
      <h3 class="public-private-label">Change to:</h3>
      <% if @recipe.public %>
        <%= button_to "Private", toggle_public_path(@recipe.id), method: :patch, class: "public-private-btn-close"  %>
      <% else %>
        <%= button_to "Public", toggle_public_path(@recipe.id), method: :patch, class: "public-private-btn"  %>
      <% end %>
    </section>
  </div>
  <div class="cooktime-desc-btn-div">
   <h2>Cooking Time: <%= @recipe.cooking_time %> </h2>
   <p> <%= @recipe.description %> </p>
   <section class="shoppinglist-ingredient-btn-div">
  <% if can? :create, @recipe %>
    <button class="gen_shopping_btn">Generate shopping list</button>
    <button class="click_btn">Add ingredient</button>
  <% end %>
  </section>
  </div>
</section>
<section class="show-table-container">
    <table>
  <tr>
    <th>Food</th>
    <th>Quantity</th>
    <th>Value</th>
    <th>Actions</th>
  </tr>
  <% @recipe_foods.each do |recipe_food| %>
    <tr>
      <td><%= recipe_food.foods.name%></td>
      <td><%= recipe_food.quantity%></td>
      <td><%= recipe_food.quantity * recipe_food.foods.price %>$</td>
      <td>
      <% if can? :edit, @recipe %>
        <button>Modify</button>
      <% end %>
      <% if can? :destroy, @recipe %>
        <%= button_to 'Delete', delete_recipe_food_path(:recipe_food_id => recipe_food.id, :recipe_id => params[:id]), method: :delete, data: {turbo_method: :delete} %>
      <% end %>
      </td>
    </tr>
  <% end %>
</table>
</section>
<section class="modal">
  <div class="modal-content">
    <button class="close_btn">X</button>
    <span>Select an ingredient:</span>
    <%= render 'recipes_food'%>
  </div>
</section>
<section class="modal_shopping">
  <div class="modal-content">
    <button class="shopping_close_btn">X</button>
    <h1>Generating Shopping List:</h1>
    <p>Choose an inventory to use:</p>
    <%= render 'shopping_list'%>
  </div>
</section>
</div>





<script>
  document.querySelector('.click_btn').addEventListener('click', (event) => {
    document.querySelector('.modal').style.visibility = 'visible'
    document.querySelector('#body').style.overflow = 'hidden'
  })

  document.querySelector('.close_btn').addEventListener('click', (event) => {
    document.querySelector('.modal').style.visibility = 'hidden'
    document.querySelector('#body').style.overflow = 'scroll'
  })

  // For shopping List
  document.querySelector('.gen_shopping_btn').addEventListener('click', (event) => {
    document.querySelector('.modal_shopping').style.visibility = 'visible'
    document.querySelector('#body').style.overflow = 'hidden'
  })

  document.querySelector('.shopping_close_btn').addEventListener('click', (event) => {
    document.querySelector('.modal_shopping').style.visibility = 'hidden'
    document.querySelector('#body').style.overflow = 'scroll'
  })

//   document.querySelectorAll('.modal-contents > div:first-of-type > span').forEach(element => {
//     element.addEventListener('click', () => {
//     document.querySelector('.recipe-modal').style.display = 'none'
//     document.querySelector('.shopping-modal').style.display = 'none'
//   })
// })
</script>