config/routes.rb
Rails.application.routes.draw do
  resources :foods, only: [:new, :create, :destroy]
  resources :recipes, only: [:new, :show, :index, :create, :destroy] do
    resources :recipes_food, only: [:create, :update]
  end

  resources :inventories, only: [:new, :show, :index, :create] do
    resources :inventories_food, only: [:create, :update]
  end
  delete '/recipes/:recipe_id/recipes_food/:recipe_food_id', to: 'recipes_food#destroy', as: 'delete_recipe_food'
  get '/shopping_lists/:recipe_id', to: 'shopping_lists#index', as: 'shopping_list'
  get '/foods', to: 'foods#index', as: 'foods_index'
  # get '/shopping_lists/:recipe_id/:inventory_id', to: 'shopping_lists#index', as: 'shopping_list'
  get '/public_recipes', to: 'recipes#public', as: 'public_recipes'
  delete '/recipes/:id', to: 'recipes#destroy', as: 'delete_recipe'
  delete '/inventories/:id', to: 'inventories#destroy', as: 'delete_inventory'
  delete '/inventories/:id/inventory_food/:id', to: 'inventories_food#destroy', as: 'delete_inventory_food'
  match '/recipes/:id' => 'recipes#toggle_public', as: :toggle_public, via: :patch

  devise_for :users
  root to: "recipes#public"

end

app/models/food.rb
class Food < ApplicationRecord
  has_many :recipe_foods, dependent: :destroy
  has_many :inventory_foods, dependent: :destroy
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.all
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    return unless @food.save!

    flash.now[:notice] = 'Food created successfully'
    redirect_to foods_path
  end

  def destroy
    @food = Food.includes(:recipe_foods).find(params[:id])
    @food.destroy
    redirect_to foods_path
  end

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/index.html.erb
<div class="food-index-container">
  <section>
    <%= link_to "<button>Add Food</button>".html_safe, new_food_path, class: 'add-food'%>
  </section>
  <table>
    <tr>
      <th>
        Food
      </th>
      <th>
        Measurement Unit
      </th>
      <th>
        Price
      </th>
      <th>
        Actions
      </th>
    </tr>
    <% @foods.each do |f| %>
      <tr>
        <td>
          <%= f.name%>
        </td>
        <td>
          <%= f.measurement_unit %>
        </td>
        <td>
          $<%= f.price %>
        </td>
        <td>
          <%= button_to 'Delete', food_path(f.id), method: :delete, data: {turbo_method: :delete} %>
        </td>
      </tr>
    <%end%>
  </table>
</div>

app/views/foods/new.html.erb
<div class="new-food-container">
  <%= form_with model:Food do |form| %>
  <ul>
    <li class="new-food-form-li">
      <%= form.label :name %>
      <%= form.text_field :name, placeholder: 'e.g Marcos Gualtero', value: '', class: "new-food-form-li-item" %>
    </li>
    <li class="new-food-form-li">
      <%= form.label :measurement_unit %>
      <%= form.text_field :measurement_unit, placeholder: 'e.g kg / grams', class: "new-food-form-li-item" %>
    </li>
    <li class="new-food-form-li">
      <%= form.label :price %>
      <%= form.number_field :price, placeholder: 'e.g $10 / $30', in: 1.0..100.0, class: "new-food-form-li-item"  %>
    </li>
    <li class="new-food-form-li-item">
      <%= form.submit "Create Food", class: "submit-new-food"%>
    </li>
  </ul>
  <% end %>
</div>